INSERT INTO tb_disciplina (codigoincricao,nome,descricao,cargahoraria,idprereq,idcurso)
VALUES
  ('ARA L63MTV61E','C#','per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel',43,38,73),
  ('ARA F28FPH45R','Python','a feugiat tellus lorem eu metus. In lorem. Donec elementum,',77,90,24),
  ('ARA S60ADK23U','C#','ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec',62,51,55),
  ('ARA R15YDE83G','Calculo I','dolor. Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer adipiscing',57,59,49),
  ('ARA F18MBK87P','Python','rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in,',54,46,20),
  ('ARA N11ZXD48S','C#','nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in',49,2,19),
  ('ARA X78HZB69C','Calculo II','Cras eu tellus eu augue porttitor interdum. Sed auctor odio',74,35,4),
  ('ARA T47DOI36I','Calculo I','nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia',75,28,18),
  ('ARA X44AHT76I','Python','Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non,',71,16,55),
  ('ARA X72MVJ47H','Web3.0','lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie.',78,50,34),
  ('ARA D92SKW18U','Web3.0','adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor',42,62,68),
  ('ARA M32WGG47L','Primeiros Socorros','tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum',78,18,82),
  ('ARA D34PVQ45Y','Calculo II','natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',69,30,19),
  ('ARA I35OEO32N','Calculo I','Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem,',48,48,15),
  ('ARA W04CTR78W','Python','imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec,',73,81,62),
  ('ARA D80YEU71L','Calculo I','convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc',77,17,19),
  ('ARA E26NTT26N','Web3.0','aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non',72,17,8),
  ('ARA Y81SUI49C','C#','et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien,',43,31,88),
  ('ARA B22WNR78L','Python','Aenean sed pede nec ante blandit viverra. Donec tempus, lorem',65,16,36),
  ('ARA N55ADW34Y','Calculo I','quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod',65,83,1),
  ('ARA F46HFZ18B','Python','sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer',69,48,22),
  ('ARA M34WWS88X','Web3.0','nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor',58,32,69),
  ('ARA D90GRU58R','Primeiros Socorros','Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien.',45,62,55),
  ('ARA X12EXG10W','Web3.0','Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla',40,10,71),
  ('ARA V64HHL35Y','Primeiros Socorros','orci, in consequat enim diam vel arcu. Curabitur ut odio',53,99,30),
  ('ARA H84RUH36L','Primeiros Socorros','Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est.',72,32,70),
  ('ARA X85CVW38N','Python','nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet',48,75,78),
  ('ARA F28FWX62G','Primeiros Socorros','amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing',79,55,65),
  ('ARA W88UNF68E','C#','adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc',66,51,8),
  ('ARA I28ISD27X','Web3.0','velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas.',47,39,73),
  ('ARA X21TVQ58G','C#','pretium neque. Morbi quis urna. Nunc quis arcu vel quam',64,15,72),
  ('ARA T32YJW86F','Calculo I','In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede',56,11,40),
  ('ARA W07IME74G','Web3.0','Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla',45,93,75),
  ('ARA R43KVZ18N','Python','Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique',40,82,35),
  ('ARA B61JFM78E','Primeiros Socorros','turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis',62,22,6),
  ('ARA C25LJX62E','Calculo II','turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed',66,41,92),
  ('ARA W75GDW24X','Primeiros Socorros','imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit,',40,90,72),
  ('ARA T69HUR03J','Primeiros Socorros','Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus.',72,33,15),
  ('ARA L11SHL93Y','Calculo I','magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla',63,54,80),
  ('ARA B60OOJ34K','Python','ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet',54,39,72),
  ('ARA Y34DSU68K','Primeiros Socorros','Cras sed leo. Cras vehicula aliquet libero. Integer in magna.',53,9,2),
  ('ARA B65ROB76N','Web3.0','ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu',48,29,45),
  ('ARA Y83DQR44N','Calculo I','ac orci. Ut semper pretium neque. Morbi quis urna. Nunc',79,46,65),
  ('ARA X97XJU14R','Web3.0','quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus',55,38,57),
  ('ARA H76AYY44G','Python','arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim.',51,81,77),
  ('ARA B25CVW73A','C#','orci, consectetuer euismod est arcu ac orci. Ut semper pretium',55,78,26),
  ('ARA R16DMJ25E','Python','Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros.',49,59,22),
  ('ARA A51WTX34R','Python','varius orci, in consequat enim diam vel arcu. Curabitur ut',53,15,29),
  ('ARA S59VOX81K','Web3.0','semper, dui lectus rutrum urna, nec luctus felis purus ac',60,71,83),
  ('ARA E52HXK44P','Web3.0','pede, ultrices a, auctor non, feugiat nec, diam. Duis mi',44,23,40);
INSERT INTO tb_disciplina (codigoincricao,nome,descricao,cargahoraria,idprereq,idcurso)
VALUES
  ('ARA L11JRK70O','Web3.0','risus. Duis a mi fringilla mi lacinia mattis. Integer eu',79,72,40),
  ('ARA E32QYX85W','Python','mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie',42,89,97),
  ('ARA O44HYB63B','Python','ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci',48,96,68),
  ('ARA Z64TPG73L','Calculo II','diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer',64,78,83),
  ('ARA J65BWC66U','Primeiros Socorros','hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer,',57,61,80),
  ('ARA W95EUY51I','Primeiros Socorros','Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae,',70,39,45),
  ('ARA B84HSN14L','Web3.0','adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor',78,100,44),
  ('ARA A18ENN64Z','Python','in lobortis tellus justo sit amet nulla. Donec non justo.',45,10,4),
  ('ARA X42GJX97M','C#','commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac,',45,86,98),
  ('ARA F14EWJ58N','Primeiros Socorros','Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin',55,49,72),
  ('ARA Q96KRH82M','Primeiros Socorros','Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis',56,13,59),
  ('ARA S06QVF53F','Primeiros Socorros','mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae,',41,11,70),
  ('ARA D67MGJ83E','Calculo I','dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu',61,60,90),
  ('ARA I20QWK84W','Primeiros Socorros','neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede',55,45,18),
  ('ARA R03QTI69P','Calculo II','sit amet, consectetuer adipiscing elit. Aliquam auctor, velit eget laoreet',42,63,80),
  ('ARA G32MZU84U','C#','dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse',52,90,97),
  ('ARA D81HPR32I','C#','mauris ipsum porta elit, a feugiat tellus lorem eu metus.',55,45,53),
  ('ARA V57PJG99M','Web3.0','pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien,',48,24,8),
  ('ARA T71KIM87N','Python','leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor',49,64,88),
  ('ARA Q87GFU68O','C#','lacus vestibulum lorem, sit amet ultricies sem magna nec quam.',52,12,77),
  ('ARA C74DSN73O','Calculo I','Duis sit amet diam eu dolor egestas rhoncus. Proin nisl',69,12,6),
  ('ARA X63OUO62S','Python','purus, in molestie tortor nibh sit amet orci. Ut sagittis',68,63,11),
  ('ARA U26ABZ12J','Web3.0','rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at,',59,87,68),
  ('ARA K56BYF01B','Web3.0','semper pretium neque. Morbi quis urna. Nunc quis arcu vel',78,50,49),
  ('ARA T33PBX55E','Calculo I','metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper',62,44,36),
  ('ARA E17YKL72C','Calculo I','Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus.',60,15,50),
  ('ARA G78WHP44O','C#','Ut semper pretium neque. Morbi quis urna. Nunc quis arcu',61,10,68),
  ('ARA J92DMU48M','Calculo II','rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed',58,29,48),
  ('ARA T55ILU59D','Calculo II','quis diam. Pellentesque habitant morbi tristique senectus et netus et',58,47,31),
  ('ARA X09NSJ44Q','Web3.0','mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin',50,99,35),
  ('ARA R68LTD21Y','Python','lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at',59,62,40),
  ('ARA J45ZBY37W','Primeiros Socorros','Proin sed turpis nec mauris blandit mattis. Cras eget nisi',68,16,32),
  ('ARA O61LVQ51H','Python','Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum',53,37,11),
  ('ARA U65ZPB57I','Python','purus. Maecenas libero est, congue a, aliquet vel, vulputate eu,',62,69,78),
  ('ARA N18GPU09G','Python','porttitor tellus non magna. Nam ligula elit, pretium et, rutrum',68,80,16),
  ('ARA B46GBP05D','Calculo I','iaculis enim, sit amet ornare lectus justo eu arcu. Morbi',60,90,49),
  ('ARA M39TMM58E','Primeiros Socorros','velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque',72,93,42),
  ('ARA I82GND87V','Calculo I','est ac facilisis facilisis, magna tellus faucibus leo, in lobortis',56,66,51),
  ('ARA X88CNO08M','Python','eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus',52,16,37),
  ('ARA X97UKN69E','Calculo I','pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus',40,69,80),
  ('ARA L56YIN59Y','Calculo II','vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce',66,51,29),
  ('ARA P35QTP64E','Calculo II','lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod',75,59,65),
  ('ARA E72SCM13O','C#','dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas',54,6,39),
  ('ARA L51KBZ92U','Web3.0','Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum',73,84,20),
  ('ARA U95MDJ16W','Calculo II','Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet',46,16,84),
  ('ARA P26GDW05I','Calculo I','convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt',61,81,98),
  ('ARA U39FTB23W','Calculo II','tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam.',62,40,43),
  ('ARA W85INW01K','Calculo II','porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor',45,64,84),
  ('ARA S87TUX43M','Calculo II','at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas',78,27,87),
  ('ARA Y71QQB46E','Calculo II','enim non nisi. Aenean eget metus. In nec orci. Donec',43,68,77);
